# Generated by Django 2.2 on 2019-05-02 11:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themyscira', '0005_auto_20190502_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='notificacion_email',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
    ]
