# Generated by Django 2.2 on 2019-05-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themyscira', '0007_requestautor_requestvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('t_id', models.CharField(max_length=100)),
            ],
        ),
    ]
